# LedisDB configuration

# Server listen address
addr = "127.0.0.1:6380"

# Server http listen address, set empty to disable
http_addr = "127.0.0.1:11181"

# Data store path, all ledisdb's data will be saved here
data_dir = "/tmp/ledis_server"

# Log server command, set empty to disable
access_log = ""

# Set slaveof to enable replication from master, empty, no replication
slaveof = ""

# Choose which backend storage to use, now support:
#
#   leveldb
#   rocksdb
#   goleveldb
#   lmdb
#   boltdb
#   hyperleveldb
#   memory
#   
db_name = "leveldb"

# If not set, use data_dir/"db_name"_data
db_path = ""

# enable replication or not
use_replication = true

[leveldb]
compression = false
block_size = 32768
write_buffer_size = 67108864
cache_size = 524288000
max_open_files = 1024

[lmdb]
map_size = 524288000
nosync = true

[replication]
# Path to store replication information(write ahead log, commit log, etc.)
# if not set, use data_dir/rpl 
path = ""

# Expire write ahead logs after the given days
expired_log_days = 7

# If sync is true, the new log must be sent to some slaves, and then commit. 
# It may affect performance. 
sync = true

# If sync is true, wait at last wait_sync_time seconds to check whether slave sync this log
wait_sync_time = 1

